version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - 'postgres-data:/bitnami/postgresql'
    networks:
      - star-wars-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - 'pg-admin-data:/var/lib/pgadmin'
    networks:
      - star-wars-network

  star-wars-backend:
    build: ./  # Ou o caminho do seu backend
    ports:
      - '3333:3333'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      - postgres  # Você ainda pode manter isso, mas não vai impactar a conexão
    networks:
      - star-wars-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - star-wars-backend
    networks:
      - star-wars-network

volumes:
  postgres-data:
  pg-admin-data:

networks:
  star-wars-network:
    driver: bridge
