"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const createCommentController_1 = require("../controllers/createCommentController");
const getCommentController_1 = require("../controllers/getCommentController");
const router = (0, express_1.Router)();
exports.router = router;
router.get('/comments', new getCommentController_1.getCommentController().handle);
router.post('/comments', new createCommentController_1.createCommentController().handle);
