name: CI/CD Pipeline


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Criar .env backend
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ./backend/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./backend/.env
          echo "POSTGRES_HOST=postgres" >> ./backend/.env
          echo "POSTGRES_PORT=5432" >> ./backend/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./backend/.env
          echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}?sslmode=disable" >> ./backend/.env

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/star-wars-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/star-wars-web:latest

      - name: Deploy to production
        run: |
          ssh ${{ secrets.PROD_SERVER_USER }}@${{ secrets.PROD_SERVER_IP }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/star-wars-backend:latest &&
            docker pull ${{ secrets.DOCKER_USERNAME }}/star-wars-web:latest
          "
