name: CI/CD - Backend e web

on:
  push:
    branches: [main]  # Roda quando der push na branch main

jobs:
  build-and-push-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/star-wars-backend ./backend

      - name: Push da imagem backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/star-wars-backend

  build-and-push-web:
    name: Build & Push web
    runs-on: ubuntu-latest
    needs: build-and-push-backend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem web
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/star-wars-web ./web

      - name: Push da imagem web
        run: docker push ${{ secrets.DOCKER_USERNAME }}/star-wars-web
